account/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import auth
from django.contrib.auth import views as auth

# from . import views as local_view
from rest_framework.authtoken import views as rest_framework_views

from account.view import get_token

app_name = "account"
urlpatterns = [

    # Session Login
    url(r'^login/$', auth.login, {'template_name': 'account/login.html'}, name="login"),
    # url(r'^login/$', auth.login, {'template_name': 'account/login.html', 'authentication_form': LoginForm}, name="login"),
    # url(r'^login/$', auth.login, name="login"),
    url(r'^logout/$', auth.logout, {'next_page': 'core:index'}, name='logout'),
    # url(r'^password/change/$', auth.password_change, {'post_change_redirect': 'account:password_change_done'}, name='password_change'),
    # url(r'^password/change/done/$', auth.password_change_done, name='password_change_done'),
    # url(r'^password/reset/$', auth.password_reset, {'post_reset_redirect': 'account:password_reset_done', 'email_template_name': 'account/mail_templates/password_reset_email.html',
    #                                                    'html_email_template_name': 'account/mail_templates/password_reset_email_html.html'}, name='password_reset'),
    # url(r'^password/reset/done/$', auth.password_reset_done, name='password_reset_done'),
    # url(r'^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth.password_reset_confirm, {'post_reset_redirect': 'account:password_reset_complete'},
    #     name='password_reset_confirm'),
    # url(r'^password/reset/complete/$', auth.password_reset_complete, name='password_reset_complete'),

]

core/urls.py
from django.conf import settings
from django.conf.urls import url, include
from rest_framework.urlpatterns import format_suffix_patterns

from core import views


app_name = "core"
urlpatterns = [
    url(r'^$', views.home, name="home"),
    url(r'^$', views.home, name="index"),
    url(r'^home/$', views.home),
    url(r'^index/$', views.home),
    url(r'^ping/$', views.ping),

    url(r'^add-type/$', views.type_add, name="add-type"),
    url(r'^edit-type/(?P<tid>%s\d{7,13})/$' % settings.SLOG_PREFIX, views.type_add, name="edit-type"),
    url(r'^type-detail/$', views.type_detail, name="type-detail"),
    url(r'^type-detail/(?P<rid>%s\d{7,13})/$' % settings.SLOG_PREFIX, views.type_detail, name="type-detail"),

    url(r'^add-retailer/$', views.retailer_add, name="add-retailer"),
    url(r'^edit-retailer/(?P<rid>%s\d{7,13})/$' % settings.SLOG_PREFIX, views.retailer_add, name="edit-retailer"),
    url(r'^retailer-detail/$', views.retailer_detail, name="retailer-detail"),
    url(r'^retailer-detail/(?P<rid>%s\d{7,13})/$' % settings.SLOG_PREFIX, views.retailer_detail, name="retailer-detail"),

    url(r'^add-store/$', views.store_add, name="add-store"),
    url(r'^edit-store/(?P<sid>%s\d{7,13})/$' % settings.SLOG_PREFIX, views.store_add, name="edit-store"),
    url(r'^store-detail/$', views.store_detail, name="store-detail"),
    url(r'^retailers-store/(?P<rid>%s\d{7,13})/$' % settings.SLOG_PREFIX, views.retailers_store, name="retailers-store"),


    url(r'^context/$', views.get_context, name="context"),

    # url(r'^api/%s/context/$' % settings.API_VERSION, views.ContextView.as_view(), name="api-context"),
    #
    # url(r'^api/%s/retailer/list/$' % settings.API_VERSION, views.api_retailer_list, name="api-retailer-list"),
    # url(r'^api/%s/retailer/list/(?P<pk>[0-9]+)/$' % settings.API_VERSION, views.api_retailer_detail, name="api-retailer-detail"),
    #
    # url(r'^api/%s/store/list/$' % settings.API_VERSION, views.api_store_list, name="api-store-list"),
    # url(r'^api/%s/store/list/(?P<pk>[0-9]+)/$' % settings.API_VERSION, views.api_store_detail, name="api-store-detail"),
    #
    # url(r'^api/%s/type/list/$' % settings.API_VERSION, views.api_type_list, name="api-type-list"),
    # url(r'^api/%s/type/list/(?P<pk>[0-9]+)/$' % settings.API_VERSION, views.api_type_detail, name="api-type-detail"),

]


# urlpatterns = format_suffix_patterns(urlpatterns)

relo_2/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from rest_framework.authtoken.views import obtain_auth_token
from rest_framework.urlpatterns import format_suffix_patterns

from account.view import get_token, Token
from core_rest.urls import schema_view

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('core.urls')),
    url(r'^api/', include('core_rest.urls')),
    # url(r'^v1/api/', include('core_rest.urls', namespace='v1')),

    url(r'^account/', include('account.urls')),
    # url(r'^api/account/token/$', obtain_auth_token, name='token'),
    url(r'^api/account/token/$', get_token, name='token'),

    url(r'^schema/$', schema_view),
]

# THIS IS A SERIOUS SECURITY LEAK, TO ENSURE YOU DON'T DO IT IN PRODUCTION, USE DEBUG TEST. BUT ENSURE DEBUG IS ALWAYS TURNED OFF IN PRODUCTION
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from uuid import uuid4

import os
from django.conf import settings
from django.core.validators import RegexValidator
from django.db import models
from django.db.models.signals import pre_save
from django.utils.translation import ugettext_lazy as _
# from storages.backends.s3boto import S3BotoStorage

# from core.signals import rename_image


def rename_and_upload(instance, filename):
    """
    Can rename or save the to a location of choice on the file system
    :param instance:
    :param filename:
    :return:
    """
    ext = filename.split('.')[-1]
    if instance.pk:
        filename = '{}.{}'.format(instance.pk, ext)
    else:
        filename = '{}.{}'.format(uuid4().hex, ext)
    return os.path.join('hell/deep', filename)


class RetailerAccount(models.Model):
    sChain = models.CharField(_('Name'), max_length=255, blank=False, null=False)
    sBanner_name = models.CharField(_('Banner Name'), max_length=255, blank=True, null=True, default=None)
    # sLogo = models.ImageField(_('Logo'), upload_to=rename_and_upload, storage=CustomS3BotoStorage(bucket=settings.AWS_LOCATION), blank=True, null=True, default=None)
    sLogo = models.ImageField(_('Logo'), upload_to=rename_and_upload, blank=True, null=True, default=None)
    sTypes = models.ManyToManyField('Type', verbose_name="Types", default=None, blank=True)

    def __str__(self):
        return self.sChain

    @property
    def logo_url(self):
        if self.sLogo and hasattr(self.sLogo, 'url'):
            return self.sLogo.url
        else:
            return "http://via.placeholder.com/50x50"

    @property
    def slugify(self):
        return "%s%d" % (settings.SLOG_PREFIX, (settings.SLOG_VALUE + self.id))


# pre_save.connect(rename_image, sender=RetailerAccount)


class StoreAccount(models.Model):
    sChain = models.ForeignKey(RetailerAccount, verbose_name="Retailer",)
    sAddOne = models.CharField(_('Add One'), max_length=255)
    sCity = models.CharField(_('City'), max_length=255)
    sState = models.CharField(_('State'), max_length=100)
    sZip = models.IntegerField(_('Zip'),)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 10 digits allowed.")
    sPhoneOne = models.CharField(_('Phone Number'), validators=[phone_regex], max_length=100)  # validators should be a list

    @property
    def retailer_account(self):
        return RetailerAccount.objects.get(pk=self.retailer_detail_id)

    @property
    def slugify(self):
        return "%s%d" % (settings.SLOG_PREFIX, (settings.SLOG_VALUE + self.id))

    def __str__(self):
        return "%s Store" % self.sChain


class Type(models.Model):
    sType = models.CharField(_('Type'), max_length=255, unique=True)

    @property
    def slugify(self):
        return "%s%d" % (settings.SLOG_PREFIX, (settings.SLOG_VALUE + self.id))

    def __str__(self):
        return self.sType

core/forms.py
from django import forms
from core.models import RetailerAccount, StoreAccount, Type


class RetailerAccountForm(forms.ModelForm):
    class Meta:
        model = RetailerAccount
        fields = '__all__'


class StoreAccountForm(forms.ModelForm):

    class Meta:
        model = StoreAccount
        fields = '__all__'


class TypeForm(forms.ModelForm):

    class Meta:
        model = Type
        fields = '__all__'

core/templates/core/base.html
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">

    <style>
        .navbar-default {
            background-color: #0066ff !important;
        }
    </style>
</head>

<body>

<nav class="navbar navbar-default" style="">
    <div class="container-fluid">
        <div class="navbar-header pull-right">
            {% if request.user.is_authenticated %}
                <a href="{% url 'account:logout' %}" class="btn btn-default">Logout</a>
            {% else %}
                <a href="{% url 'account:login' %}" class="btn btn-default">Login</a>
            {% endif %}

        </div>
    </div>
</nav>

<div class="container">
    <table class="table" id="table-context">
        <thead>
            <tr>
                <th> Retailers</th>
                <th> Stores</th>
                <th> Missing Logo</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td> <a href="{% url 'core:retailer-detail' %}" title="View Stores" id="account-count"> {{ accounts }}</a></td>
                <td> <a href="{% url 'core:store-detail' %}" title="View Stores" id="store-count"> {{ stores }}</a></td>
                <td id="null-logo-count"> {{ null_logo }}</td>

            </tr>
        </tbody>
    </table>
</div>


{% block content %}

{% endblock %}


<script type="text/javascript" src="{% static 'jQuery/jquery-2.2.3.min.js' %}"></script>
<script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>

<link rel="stylesheet" type="text/css" href="{% static 'bootstrap3-dialog/css/bootstrap-dialog.min.css' %}">
<script type="text/javascript" src="{% static 'bootstrap3-dialog/js/bootstrap-dialog.min.js' %}"></script>
<script src="{% static 'js-cookie/js-cookie.js' %}"></script>

<script>
    function pwd(msg, closable) {
        closable = closable ? true : false;
        var pleaseWaitDialog = new BootstrapDialog({
            message: '<p class="text-center">' + msg + '</p>',
            closeButton: false,
            closable: closable,
            closeByBackdrop: closable,
            closeByKeyboard: closable,
        });
        pleaseWaitDialog.realize();
        pleaseWaitDialog.getModalFooter().hide();
        pleaseWaitDialog.getModalHeader().hide();
        pleaseWaitDialog.open();
        return pleaseWaitDialog;
    }

    function csrfSafeMethod(method) {
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

    function processFeed(url, data, blocking_msg, asJson, method, successCallback, errorCallback) {
        var pwDialog = null;
        $.ajax({
            type: method,
            url: url,
            data: data,
            dataType: "json",
            processData: (asJson==null || asJson==false),
            contentType: (this.processData? 'application/x-www-form-urlencoded; charset=utf-8':'application/json; charset=utf-8'),
            beforeSend: function (xhr, settings) {
                console.log(this.data)
                var csrftoken = Cookies.get('csrftoken');
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
                console.log("sending to: ", this.url)
                if (blocking_msg != null) {
                    pwDialog = pwd(blocking_msg);
                }
            },
            success: function (d) {
                if (typeof successCallback === "function") {
                    successCallback(d);
                }
            },
            error: function (d) {
                if (typeof errorCallback === "function") {
                    errorCallback(d);
                }
            },
            complete: function (d) {
                if (blocking_msg != null) {
                    pwDialog.close();
                }
            }
        });
    }

    $(document).ready(function () {
        processFeed("{% url 'core:context' %}", {}, null, false, 'GET', function(d){
            $.each(Object.keys(d), function (i, v) {
                if ("context,accounts,stores,null_logo".indexOf(v) == -1) {
                    $("#table-context thead tr").append("<th>" + v + "</th>")
                    $("#table-context tbody tr").append("<td>" + d[v] + "</td>")
                }
            });
            $("#account-count").html(d["accounts"]);
            $("#store-count").html(d["stores"]);
            $("#null-logo-count").html(d["null_logo"]);
        }, function (d) {
            console.log("Something went Wrong: ", d.responseText)
        });
    });
</script>
{% block javascript %}
{% endblock %}


</body>
</html>

core/templates/core/create_account.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags static %}

{% block content %}
  <div class="row">
    <div class ='col-sm-6 col-sm-offset-3'>
        <form  action="" method="POST" class="form-group" >
            {% csrf_token %}
            {{form|crispy}}
            <button type="submit" class="btn btn-default">Submit</button>

        </form>
    </div>
  </div>

{% endblock %}

{% block javascript %}

    <link rel="stylesheet" type="text/css" href="{% static 'select2/css/select2.min.css' %}">
    <script type="text/javascript" src="{% static 'select2/js/select2.min.js' %}"></script>
    <script>
        $(document).ready(function() {
            $('#id_retailer_detail_id').select2({width: '100%'});
        });
    </script>
{% endblock %}

core/templates/core/retailer_account.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags static %}
{% block content %}


    <div class="row">
        <div class='col-sm-6 col-sm-offset-3'>
            <form action="" method="POST" class="form-group" role="search" enctype="multipart/form-data">
                {% csrf_token %}

                {{ form|crispy }}
                <button type="submit" class="btn btn-info">Save</button>

            </form>

        </div>
    </div>

{% endblock %}

{% block javascript %}
    <link rel="stylesheet" type="text/css" href="{% static 'select2/css/select2.min.css' %}">
    <script type="text/javascript" src="{% static 'select2/js/select2.min.js' %}"></script>
    <script>

        $(document).ready(function() {
            $('#id_sTypes').select2({width: '100%'});
        });
    </script>
{% endblock %}

core/templates/core/retailer_add_account.html
{% load rest_framework %}

<html><body>


<form action="{% url  pk=add_account.pk %}" method="POST">
    {% csrf_token %}
    {% render_form serializer %}
    <input type="submit" value="Save">
</form>

</body></html>

core/templates/core/retailer_add_account_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>


<form method="POST" id="post-form">
    {% csrf_token %}
    <div class="fieldWrapper" id="the_post">
        {{ form }}
    </div>
    <div id="results"></div> <!-- errors go here -->
    <input type="submit" value="Post" class="tiny button">
</form>
</body>
<script>
function create_post() {
    console.log("create post is working!") // sanity check
    $.ajax({
        url : "create_post/", // the endpoint
        type : "POST", // http method
        data : { the_post : $('#post-text').val() }, // data sent with the post request

        // handle a successful response
        success : function(json) {
            $('#post-text').val(''); // remove the value from the input
            console.log(json); // log the returned json to the console
            console.log("success"); // another sanity check
        },

        // handle a non-successful response
        error : function(xhr,errmsg,err) {
            $('#results').html("<div class='alert-box alert radius' data-alert>Oops! We have encountered an error: "+errmsg+
                " <a href='#' class='close'>&times;</a></div>"); // add the error to the dom
            console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
        }
    });
};


</script>
</html>

core/templates/core/retailer_detail.html
{% extends 'core/base.html' %}
{% load static i18n paginate %}

{% block content %}

    <br>
    <div class="container">

        <div class="row">
            <div class="col-sm-6">
                <form action="" method="GET" id="search-form">{% csrf_token %}
                    <div class="input-group input-group-sm">
                        <input type="text" class="form-control" id="search-query" name="q" value="{{ q|default:'' }}" placeholder="Search for...">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="submit" id="search-button"><i class="glyphicon glyphicon-search"></i> </button>
                        </span>
                    </div><!-- /input-group -->
                </form>
            </div>

            <div class="col-sm-6">
                <a href="{% url 'core:add-retailer' %}" class="btn btn-primary pull-right"><i class="glyphicon glyphicon-plus"></i> Add Retailer</a>
            </div>
        </div><!-- /.row -->

            <table class="table" id="retailer-table">
                <thead>
                    <tr>
                        <th>Account Name</th>
                        <th> Banner</th>
                        <th> Type <a href="{% url 'core:add-type' %}"><i class="glyphicon glyphicon-plus"></i></a> </th>
                        <th> Logo</th>
                        <th> Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for data in context %}
                        <tr>
                            <td><a href="{% url 'core:retailers-store' data.slugify %}">{{ data.sChain }}</a></td>
                            <td> {{ data.sBanner_name }}</td>
                            <td> {{ data.sTypes.all|join:", " }} </td>
                            <td><img src="{{ data.logo_url }}" width="50"></td>
                            <td><a href="{% url 'core:edit-retailer' data.slugify %}" title="Click to Edit {{ data.sChain }}"><i class="glyphicon glyphicon-edit"></i></a></td>
                        </tr>
                    {% endfor %}
                </tbody>

            </table>


            {{ context|paginate_to:"10,True" }}
    </div>
{% endblock %}


{% block javascript %}
    <script>
        $(document).ready(function () {
            $("#search-form").submit(function (d) {
                d.preventDefault();
                location.href = "./?q="+$("#search-query").val();
            })
        });
    </script>
{% endblock %}

core/templates/core/store_detail.html
{% extends 'core/base.html' %}

{% load i18n paginate %}

{% block content %}

    <div class="container">

        <div class="row">
            <div class="col-sm-6">
                <form action="" method="GET" id="search-form">{% csrf_token %}
                    <div class="input-group input-group-sm">
                        <input type="text" class="form-control" id="search-query" name="q" value="{{ q|default:'' }}" placeholder="Search for...">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="submit" id="search-button"><i class="glyphicon glyphicon-search"></i> </button>
                        </span>
                    </div><!-- /input-group -->
                </form>
            </div>

            <div class="col-sm-6">
              <a href="{% url 'core:add-store' %}" class="btn btn-primary pull-right">
                  <i class="glyphicon glyphicon-plus"></i> Add Store</a>
            </div>
        </div><!-- /.row -->


        <table class="table">
            <thead>
                <tr>
                    <th>Store Name</th>
                    <th>Add One</th>
                    <th>City</th>
                    <th>State</th>
                    <th>Zip</th>
                    <th>Phone Number</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for data in context %}
                    <tr>
                        <td> <a href="{% url 'core:retailer-detail' data.slugify  %}">{{ data.sChain }}</a> </td>
                        <td> {{ data.sAddOne }}</td>
                        <td> {{ data.sCity }}</td>
                        <td> {{ data.sState }}</td>
                        <td> {{ data.sZip }}</td>
                        <td> {{ data.sPhoneOne }}</td>
                        <td> <a href="{% url 'core:edit-store' data.slugify %}" title="Click to Edit {{ data.sChain }}"><i class="glyphicon glyphicon-edit"></i> </a> </td>
                    </tr>
                {% endfor %}
            </tbody>

        </table>
        {{ context|paginate_to:"10,True" }}
    </div>
{% endblock %}

{% block javascript %}
    <script>
        $(document).ready(function () {
            $("#search-form").submit(function (d) {
                d.preventDefault();
                location.href = "./?q="+$("#search-query").val();
            })
        });
    </script>
{% endblock %}

core/templates/core/type_create.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags static %}
{% block content %}


    <div class="row">
        <div class='col-sm-6 col-sm-offset-3'>
            <form action="" method="POST" class="form-group" >
                {% csrf_token %}

                {{ form|crispy }}
                <button type="submit" class="btn btn-info">Save</button>

            </form>

        </div>
    </div>

{% endblock %}

{% block javascript %}
{% endblock %}

core/templates/core/type_detail.html
{% extends 'core/base.html' %}
{% load static i18n paginate %}

{% block content %}

    <div class="container">

        <div class="row">
            <div class="col-sm-6">
                <form action="" method="GET" id="search-form">{% csrf_token %}
                    <div class="input-group input-group-sm">
                        <input type="text" class="form-control" id="search-query" name="q" value="{{ q|default:'' }}" placeholder="Search for...">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="submit" id="search-button"><i class="glyphicon glyphicon-search"></i> </button>
                        </span>
                    </div><!-- /input-group -->
                </form>
            </div>

            <div class="col-sm-6">
              <a href="{% url 'core:add-type' %}" class="btn btn-primary pull-right"><i class="glyphicon glyphicon-plus"></i> Add Type</a>
            </div>
        </div><!-- /.row -->

        <table class="table">
            <thead>
                <tr>
                    <th> Name</th>
                </tr>
            </thead>
            <tbody>
                {% for data in context %}
                    <tr>
                        <td> <a href="{% url 'core:type-detail' data.slugify  %}">{{ data }}</a> </td>
                    </tr>
                {% endfor %}
            </tbody>

        </table>

        {{ context|paginate_to:"10,True" }}

    </div>


{% endblock %}

{% block javascript %}
    <script>
        $(document).ready(function () {
            $("#search-form").submit(function (d) {
                d.preventDefault();
                location.href = "./?q="+$("#search-query").val();
            })
        });
    </script>
{% endblock %}