core/urls.py
from django.conf import settings
from django.conf.urls import url, include
from rest_framework.urlpatterns import format_suffix_patterns

from core import views


app_name = "core"
urlpatterns = [
    url(r'^$', views.home, name="home"),
    url(r'^$', views.home, name="index"),
    url(r'^home/$', views.home),
    url(r'^index/$', views.home),
    url(r'^ping/$', views.ping),

    url(r'^add-type/$', views.type_add, name="add-type"),
    url(r'^edit-type/(?P<tid>%s\d{7,13})/$' % settings.SLOG_PREFIX, views.type_add, name="edit-type"),
    url(r'^type-detail/$', views.type_detail, name="type-detail"),
    url(r'^type-detail/(?P<rid>%s\d{7,13})/$' % settings.SLOG_PREFIX, views.type_detail, name="type-detail"),

    url(r'^add-retailer/$', views.retailer_add, name="add-retailer"),
    url(r'^edit-retailer/(?P<rid>%s\d{7,13})/$' % settings.SLOG_PREFIX, views.retailer_add, name="edit-retailer"),
    url(r'^retailer-detail/$', views.retailer_detail, name="retailer-detail"),
    url(r'^retailer-detail/(?P<rid>%s\d{7,13})/$' % settings.SLOG_PREFIX, views.retailer_detail, name="retailer-detail"),

    url(r'^add-store/$', views.store_add, name="add-store"),
    url(r'^edit-store/(?P<sid>%s\d{7,13})/$' % settings.SLOG_PREFIX, views.store_add, name="edit-store"),
    url(r'^store-detail/$', views.store_detail, name="store-detail"),
    url(r'^retailers-store/(?P<rid>%s\d{7,13})/$' % settings.SLOG_PREFIX, views.retailers_store, name="retailers-store"),


    url(r'^context/$', views.get_context, name="context"),

    # url(r'^api/%s/context/$' % settings.API_VERSION, views.ContextView.as_view(), name="api-context"),
    #
    # url(r'^api/%s/retailer/list/$' % settings.API_VERSION, views.api_retailer_list, name="api-retailer-list"),
    # url(r'^api/%s/retailer/list/(?P<pk>[0-9]+)/$' % settings.API_VERSION, views.api_retailer_detail, name="api-retailer-detail"),
    #
    # url(r'^api/%s/store/list/$' % settings.API_VERSION, views.api_store_list, name="api-store-list"),
    # url(r'^api/%s/store/list/(?P<pk>[0-9]+)/$' % settings.API_VERSION, views.api_store_detail, name="api-store-detail"),
    #
    # url(r'^api/%s/type/list/$' % settings.API_VERSION, views.api_type_list, name="api-type-list"),
    # url(r'^api/%s/type/list/(?P<pk>[0-9]+)/$' % settings.API_VERSION, views.api_type_detail, name="api-type-detail"),

]


# urlpatterns = format_suffix_patterns(urlpatterns)

product/urls.py
from django.conf import settings
from django.conf.urls import url

from product import views
from product.views import BrandAccountCreateView

app_name = "product"
urlpatterns = [
    url(r'^$', views.index, name="index"),

    url(r'^brand/add/$', views.brand_create, name="brand-add"),
    url(r'^brand/detail/$', views.brand_detail, name="brand-detail"),
    url(r'^brand/detail/(?P<bid>%s\d{7,13})/$' % settings.SLOG_PREFIX, views.brand_detail, name="brand-detail"),

    url(r'^brand-account/add/$', views.brand_account_create, name="brand-account-add"),
    url(r'^brand-account/detail/$', views.brand_account_detail, name="brand-account-detail"),
    url(r'^brand-account/detail/(?P<bid>%s\d{7,13})/$' % settings.SLOG_PREFIX, views.brand_detail, name="brand-account-detail"),

    # url(r'^brand-account/add/$', BrandAccountCreateView.as_view(), name="account-brand-add"),
]

relo_2/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from rest_framework.authtoken.views import obtain_auth_token
from rest_framework.urlpatterns import format_suffix_patterns

from account.view import get_token, Token
from core_rest.urls import schema_view

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('core.urls')),
    url(r'^api/', include('core_rest.urls')),
    # url(r'^v1/api/', include('core_rest.urls', namespace='v1')),

    url(r'^account/', include('account.urls')),
    # url(r'^api/account/token/$', obtain_auth_token, name='token'),
    url(r'^api/account/token/$', get_token, name='token'),

    url(r'^schema/$', schema_view),
]

# THIS IS A SERIOUS SECURITY LEAK, TO ENSURE YOU DON'T DO IT IN PRODUCTION, USE DEBUG TEST. BUT ENSURE DEBUG IS ALWAYS TURNED OFF IN PRODUCTION
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/models.py
from uuid import uuid4

import os
from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.translation import ugettext_lazy as _

# Create your models here.
from django.urls import reverse


class Brand(models.Model):
    name = models.CharField(max_length=64)

    @property
    def slugify(self):
        return "%s%d" % (settings.SLOG_PREFIX, (settings.SLOG_VALUE + self.id))

    def __str__(self):
        return self.name


def rename_and_upload(instance, filename):
    """
    Can rename or save the to a location of choice on the file system
    :param instance:
    :param filename:
    :return:
    """
    ext = filename.split('.')[-1]
    if instance.pk:
        filename = '{}.{}'.format(instance.pk, ext)
    else:
        filename = '{}.{}'.format(uuid4().hex, ext)
    return os.path.join('hell/deep', filename)


def validate_file_extension(value):
    ext = os.path.splitext(value.name)[1]
    valid_extensions = ['.pdf', '.zip', '.jpj', '.png']
    if not ext.lower() in valid_extensions:
        raise ValidationError('Allowed files are .pdf, .zip, .jpj, .png')


def validate_file(file_obj):
    mb_limit = 50.0
    if file_obj.file.size > mb_limit*1024*1024:
        raise ValidationError('File size is larger than the allowed Limit 50mb')


class BrandAccount(models.Model):
    PENDING = 'Pending'; REVIEWED = 'Reviewed'
    STATUS = (PENDING, _('Pending')), (REVIEWED, _('Reviewed'))
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    file = models.FileField(upload_to=rename_and_upload, validators=[validate_file, validate_file_extension], blank=True, null=True, default=None)
    website = models.URLField(blank=True, null=True, default=None)
    name = models.CharField(max_length=256, blank=True, null=True, default=None)
    email = models.EmailField(max_length=255, blank=True, null=True, default=None)
    title = models.CharField(max_length=255, blank=True, null=True, default=None)
    status = models.CharField(choices=STATUS, default=PENDING, max_length=10)
    reviewed_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True, default=None)

    def __str__(self):
        return self.brand.name if self.name is None else "{} ({})".format(self.brand.name, self.name)

    def get_absolute_url(self):
        return reverse('core:upload-new',)

    @property
    def slugify(self):
        return "%s%d" % (settings.SLOG_PREFIX, (settings.SLOG_VALUE + self.id))

            # def save(self, *args, **kwargs):
    #     self.slug = self.file.name
    #     super(BrandAccount, self).save(*args, **kwargs)
    #
    # def delete(self, *args, **kwargs):
    #     """delete -- Remove to leave file."""
    #     self.file.delete(False)
    #     super(BrandAccount, self).delete(*args, **kwargs)

product/forms.py
from django import forms

from product.models import BrandAccount, Brand


class BrandForm(forms.ModelForm):
    class Meta:
        model = Brand
        fields = '__all__'


class BrandAccountForm(forms.ModelForm):
    class Meta:
        model = BrandAccount
        fields = ('brand', 'title', 'website', 'email', 'name', 'file')

product/views.py
import json

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.contenttypes.models import ContentType
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

from product.response import response_mimetype, JSONResponse, serialize
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.
from django.template import context
from django.urls import reverse
from django.views.generic import CreateView

from core.utils import get_real_id
from product.forms import BrandAccountForm, BrandForm
from product.models import BrandAccount, Brand


def index(request):

    return render(request, 'product/create_brand.html', context={})


@login_required
def brand_create(request, bid=None):
    if bid:
        brand = get_object_or_404(BrandAccount, id=get_real_id(bid))
    else:
        brand = None

    if request.method == "POST":
        form = BrandForm(request.POST, instance=brand)
        if form.is_valid():
            form.save()
            return redirect(reverse("product:brand-detail"))
    else:
        form = BrandForm(instance=brand)
    return render(request, 'product/brand_create.html', context={'form': form})


@login_required
def brand_detail(request, bid=None):
    if bid:
        context = [Brand.objects.filter(id=get_real_id(bid))]
    else:
        context = Brand.objects.all()

    q = request.GET.get('q', None)
    if q:
        context = context.filter(name__icontains=q)

    page = request.GET.get('page', 1)

    paginator = Paginator(context, 4)
    try:
        context = paginator.page(page)
    except PageNotAnInteger:
        context = paginator.page(1)
    except EmptyPage:
        context = paginator.page(paginator.num_pages)

    return render(request, 'product/brand_detail.html', context={'context': context, 'q': q})


@login_required
def brand_account_create(request, bid=None):
    if bid:
        brand = get_object_or_404(BrandAccount, id=get_real_id(bid))
    else:
        brand = None
    if request.method == 'POST':
        form = BrandAccountForm(request.POST, request.FILES, instance=brand)
        if form.is_valid():
            form.save()
            return redirect(reverse("product:brand-account-detail"))
    else:
        form = BrandAccountForm(instance=brand)
    return render(request, 'product/brand_account_create.html', context={'form': form})


@login_required
def brand_account_detail(request, bid=None):
    if bid:
        context = [BrandAccount.objects.filter(id=get_real_id(bid))]
    else:
        context = BrandAccount.objects.all()

    q = request.GET.get('q', None)
    if q:
        context = context.filter(Q(bran__name__icontains=q) | Q(name__icontains=q) | Q(website__icontains=q) | Q(email__icontains=q) | Q(title__icontains=q))

    page = request.GET.get('page', 1)

    paginator = Paginator(context, 4)
    try:
        context = paginator.page(page)
    except PageNotAnInteger:
        context = paginator.page(1)
    except EmptyPage:
        context = paginator.page(paginator.num_pages)

    return render(request, 'product/brand_account_detail.html', context={'context': context, 'q': q})


class BrandAccountCreateView(LoginRequiredMixin, CreateView):
    model = BrandAccount
    fields = ('brand', 'website', 'name', 'email', 'title', 'file')
    template_name = 'product/brand_account_create.html'

    def get_context_data(self, **kwargs):
        context = super(BrandAccountCreateView, self).get_context_data(**kwargs)
        context['maxImageSize'] = 50*1024*1024
        return context

    def form_valid(self, form):
        # TODO: Find away to report this error on the template, it is not reported
        def invalidate(msg):
            errors = form.errors.copy()
            errors.update({'file_size': msg})
            if self.request.is_ajax():
                return HttpResponse(content=json.dumps(errors), status=400, content_type='application/json')
            else:
                return super(JSONResponse, self).form_invalid(form)

        if int(form.files['file'].size) > (50*1024*1024):
            return invalidate("File size too large");

        self.object = form.save()
        data = {'files': [serialize(self.object)]}
        response = JSONResponse(data, mimetype=response_mimetype(self.request))
        response['Content-Disposition'] = 'inline; filename=files.json'
        return response
        # return super(POPCreateView, self).form_valid(form)

    def form_invalid(self, form):
        data = json.dumps(form.errors)
        if self.request.is_ajax():
            return HttpResponse(content=data, status=400, content_type='application/json')
        else:
            return super(JSONResponse, self).form_invalid(form)

product/templates/product/base.html
{% extends 'core/base.html' %}


{% block content %}


{% endblock %}

{% block javascript %}

{% endblock %}

product/templates/product/brand_account_create.html
{% extends 'product/base.html' %}
{% load crispy_forms_tags static %}

{% block content %}
    <div class="row">
        <div class='col-sm-10 col-sm-offset-1'>
            <form action="" method="POST" id="brandfrom" class="form-group" enctype='multipart/form-data'>
                <div class="col-sm-6">
                    <span class="btn btn-default fileinput-button">
                        <i class="glyphicon glyphicon-plus"></i>
                        <span>Add file...</span>
                        {{ form.file }}
                    </span>
                </div>
                <div class="col-sm-6">
                    {% csrf_token %}
                    {{ form.brand|as_crispy_field }}
                    {{ form.title|as_crispy_field }}
                    {{ form.website|as_crispy_field }}
                    {{ form.email|as_crispy_field }}
                    {{ form.name|as_crispy_field }}
                    <button type="submit" name="Save" id="save" value="">Save</button>
                </div>
            </form>
        </div>
    </div>

    <style>
        .file-drop-zone{max-height: 280px;}
    </style>
{% endblock %}

{% block javascript %}

    <link rel="stylesheet" type="text/css" href="{% static 'select2/css/select2.min.css' %}">
    <script type="text/javascript" src="{% static 'select2/js/select2.min.js' %}"></script>

    <link rel="stylesheet" href="{% static 'bootstrap-fileinput/css/fileinput.min.css' %}"/>
    <script src="{% static 'bootstrap-fileinput/js/fileinput.min.js' %}"></script>

    <!-- js-cookie 2.1.3 -->
    <script src="{% static 'js-cookie/js-cookie.js' %}"></script>

    <script>
        $(document).ready(function () {
            $('#id_brand').select2({width: '100%'});
            console.log({csrfmiddlewaretoken: $("input[name='csrfmiddlewaretoken']").val(), brand:$("#id_brand").val(), website: $("#id_website").val(), name: $("#id_name").val(), email: $("#id_email").val(), title: $("#id_title").val(), })

            $("#id_file").fileinput({
                showPreview: true,
                showUpload: false,
                showRemove: true,
                previewFileType: 'any',
                removeFromPreviewOnError: false,
                initialPreview: [],
                maxFileCount: 1,
                initialPreviewAsData: true,
                allowedPreviewTypes: 'image',
                maxFileSize: parseFloat('{{ maxUploadSize }}'),
                uploadAsync: true,
                allowedFileExtensions: ['jpeg', 'jpg', 'png', 'pdf', 'zip'],
                uploadUrl: '{% url "product:brand-account-add" %}',
                initialCaption: "Product",
                uploadExtraData: {csrfmiddlewaretoken: $("input[name='csrfmiddlewaretoken']").val(), brand:$("#id_brand").val(), website: $("#id_website").val(), name: $("#id_name").val(), email: $("#id_email").val(), title: $("#id_title").val(), }
            });

{#            $("#id_file").on('fileuploaded', function (event, data, previewId, index) {#}
{#                bootbox.alert("POP successfully uploaded, please wait while the receiver confirms your payment", function () {#}
{#                    location.href = './'#}
{#                });#}
{#            });#}


            $('#save').on('click', function (e) {
                e.preventDefault();
                var formCol = $('#brandfrom');
                $.ajax({
                    type: 'POST',
                    url: '{% url "product:brand-account-add" %}',
                    data: new FormData(formCol[0]),
                    processData: false,
                    contentType: false,
                    success: function (data) {
                        alert('Succsess');
                        location.href = "."
                    }
                });
            });
        });
    </script>
{% endblock %}

product/templates/product/brand_account_detail.html
{% extends 'product/base.html' %}
{% load static i18n paginate mathfilters %}

{% block content %}

    <br>
    <div class="container">

        <div class="row">
            <div class="col-sm-6">
                <form action="" method="GET" id="search-form">{% csrf_token %}
                    <div class="input-group input-group-sm">
                        <input type="text" class="form-control" id="search-query" name="q" value="{{ q|default:'' }}" placeholder="Search for...">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="submit" id="search-button"><i class="glyphicon glyphicon-search"></i> </button>
                        </span>
                    </div><!-- /input-group -->
                </form>
            </div>

            <div class="col-sm-6">
                <a href="{% url 'product:brand-account-add' %}" class="btn btn-primary pull-right"><i class="glyphicon glyphicon-plus"></i> Add Brand Account</a>
            </div>
        </div><!-- /.row -->

            <table class="table" id="brand-table">
                <thead>
                    <tr>
                        <th>Upload ID</th>
                        <th>Brand</th>
                        <th>Contact</th>
                        <th>Title</th>
                        <th>Email</th>
                        <th>Website</th>
                        <th>File Name</th>
                        <th>Size</th>
                        <th>Reviewer</th>
                        <th>Status</th>
                        <th>Updated</th>
                        <th>Note</th>
                        <th>Download</th>
                    </tr>
                </thead>
                <tbody>
                    {% for data in context %}
                        <tr>
                            <td>-</td>
                            <td>{{ data.brand.name }}</td>
                            <td>{{ data.name }}</td>
                            <td>{{ data.title }}</td>
                            <td><a href="mailto:{{ data.email }}">{{ data.email }}</a></td>
                            <td><a href="{{ data.website }}" target="_blank">{{ data.website }}</a></td>
                            <td style="max-width: 100px; overflow: hidden">{{ data.file.name|default:"-" }}</td>
                            <td>{{ data.file.size|default:"0"|intdiv:1024 }}kb</td>
                            <td>{{ data.reviewer|default:"-" }}</td>
                            <td>{{ data.status }}</td>
                            <td>{{ data.created }}</td>
                            <td>{{ data.note }}</td>
                            <td><a href="{{ data.file.url|default:"javascript:;" }}" download="{{ data.title|default:'' }}" target="_blank"><i class="glyphicon glyphicon-download"></i> </a></td>
                        </tr>
                    {% endfor %}
                </tbody>

            </table>


            {{ context|paginate_to:"10,True" }}
    </div>
{% endblock %}


{% block javascript %}
    <script>
        $(document).ready(function () {
            $("#search-form").submit(function (d) {
                d.preventDefault();
                location.href = "./?q="+$("#search-query").val();
            })
        });
    </script>
{% endblock %}

product/templates/product/brand_create.html
{% extends 'product/base.html' %}
{% load crispy_forms_tags static %}

{% block content %}
  <div class="row">
    <div class ='col-sm-6 col-sm-offset-3'>
        <form  action="" method="POST" class="form-group" >
            {% csrf_token %}
            {{form|crispy}}
            <button type="submit" class="btn btn-default">Submit</button>

        </form>
    </div>
  </div>

{% endblock %}

{% block javascript %}

{% endblock %}

product/templates/product/brand_detail.html
{% extends 'product/base.html' %}
{% load static i18n paginate %}

{% block content %}

    <br>
    <div class="container">

        <div class="row">
            <div class="col-sm-6">
                <form action="" method="GET" id="search-form">{% csrf_token %}
                    <div class="input-group input-group-sm">
                        <input type="text" class="form-control" id="search-query" name="q" value="{{ q|default:'' }}" placeholder="Search for...">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="submit" id="search-button"><i class="glyphicon glyphicon-search"></i> </button>
                        </span>
                    </div><!-- /input-group -->
                </form>
            </div>

            <div class="col-sm-6">
                <a href="{% url 'product:brand-add' %}" class="btn btn-primary pull-right"><i class="glyphicon glyphicon-plus"></i> Add Brand</a>
            </div>
        </div><!-- /.row -->

            <table class="table" id="brand-table">
                <thead>
                    <tr>
                        <th>Brand Name</th>
                    </tr>
                </thead>
                <tbody>
                    {% for data in context %}
                        <tr>
                            <td><a href="{% url 'product:brand-detail' data.slugify %}">{{ data.name }}</a></td>
                        </tr>
                    {% endfor %}
                </tbody>

            </table>


            {{ context|paginate_to:"10,True" }}
    </div>
{% endblock %}


{% block javascript %}
    <script>
        $(document).ready(function () {
            $("#search-form").submit(function (d) {
                d.preventDefault();
                location.href = "./?q="+$("#search-query").val();
            })
        });
    </script>
{% endblock %}